# Generated by Django 4.2 on 2024-10-23 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0002_alter_productos_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('cedula', models.CharField(blank=True, max_length=10, null=True)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('metodo_de_pago', models.IntegerField(blank=True, null=True)),
                ('metodo_de_venta', models.IntegerField(blank=True, max_length=10, null=True)),
                ('total', models.FloatField(blank=True, max_length=10, null=True)),
                ('estado', models.IntegerField(blank=True, max_length=10, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cod_Venta', models.CharField(blank=True, max_length=10, null=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cliente', to='ventas.cliente', verbose_name='cliente')),
            ],
        ),
        migrations.CreateModel(
            name='VentaItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('cantidad', models.IntegerField(blank=True, max_length=10, null=True)),
                ('total', models.IntegerField(blank=True, max_length=10, null=True)),
                ('codigo_venta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Venta', to='ventas.venta', verbose_name='Venta')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cliente', to='productos.productos', verbose_name='cliente')),
            ],
        ),
    ]
