# Generated by Django 4.2 on 2024-10-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_ventaitems_codigo_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='cod_Venta',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
