# Generated by Django 4.2 on 2024-11-04 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_alter_venta_cod_venta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventaitems',
            old_name='codigo_venta',
            new_name='id_venta',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='cod_Venta',
        ),
    ]
