# Generated by Django 4.2 on 2024-11-04 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_productos_estado_productos_imagen'),
        ('ventas', '0005_rename_codigo_venta_ventaitems_id_venta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventaitems',
            name='cantidad',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ventaitems',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='producto', to='productos.productos', verbose_name='producto'),
        ),
    ]
