# Generated by Django 4.2 on 2024-11-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_remove_ventaitems_cantidad_alter_cliente_cedula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaitems',
            name='cantidad',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
