# Generated by Django 4.2 on 2024-11-04 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_productos_estado_productos_imagen'),
        ('ventas', '0007_ventaitems_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ventas', to='ventas.cliente', verbose_name='cliente'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='metodo_de_venta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ventaitems',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ventaitems',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='venta_items', to='productos.productos', verbose_name='producto'),
        ),
        migrations.AlterField(
            model_name='ventaitems',
            name='id_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='ventas.venta', verbose_name='Venta'),
        ),
        migrations.AlterField(
            model_name='ventaitems',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
