# Generated by Django 4.2 on 2024-11-05 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_productos_estado_productos_imagen'),
        ('ventas', '0008_alter_venta_estado_alter_venta_id_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cliente', to='ventas.cliente', verbose_name='cliente'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='metodo_de_venta',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ventaitems',
            name='cantidad',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ventaitems',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cliente', to='productos.productos', verbose_name='cliente'),
        ),
        migrations.AlterField(
            model_name='ventaitems',
            name='id_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Venta', to='ventas.venta', verbose_name='Venta'),
        ),
        migrations.AlterField(
            model_name='ventaitems',
            name='total',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
