# Generated by Django 4.2 on 2024-11-13 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_alter_venta_estado_alter_venta_id_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventaitems',
            name='id_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='ventas.venta', verbose_name='Venta'),
        ),
        migrations.CreateModel(
            name='AbonosCuentas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('valor', models.IntegerField(blank=True, max_length=10, null=True)),
                ('deuda_restante', models.IntegerField(blank=True, max_length=10, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cedula_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='ventas.cliente', to_field='cedula')),
            ],
        ),
    ]
