# Generated by Django 4.2 on 2024-11-10 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_alter_venta_estado_alter_venta_id_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventaitems',
            name='id_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='ventas.venta', verbose_name='Venta'),
        ),
    ]
